version: '2'

services:

  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-le
    restart: always
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/nginx/acme:/etc/acme.sh
    volumes_from:
      - nginx

  mariadb:
    image: mariadb:10.5
    restart: always
    container_name: mariadb-***REMOVED***
#    ports:
#      - 10.7.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - /data/mysql:/var/lib/mysql
      - /data/mysql-backup:/var/lib/backup
      - ./mariadb-config:/etc/mysql/conf.d

  redis:
    image: redis
    restart: always
    container_name: redis

  nextcloud-app:
    build: ./nextcloud-app
    restart: always
    container_name: nextcloud-app
    volumes:
      - /data/nextcloud/html:/var/www/html
      - /data/nextcloud/data:/var/www/html/data
      - /data/nextcloud/config:/var/www/html/config
      - /data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/themes:/var/www/html/themes
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
      - redis
      - letsencrypt

  nextcloud-web:
    build: ./nextcloud-web
    restart: always
    container_name: nextcloud-web
    expose:
      - 443
    volumes:
      - /data/nextcloud/html:/var/www/html:ro
      - /data/nextcloud/data:/var/www/html/data:ro
      - /data/nextcloud/config:/var/www/html/config:ro
      - /data/nextcloud/custom_apps:/var/www/html/custom_apps:ro
      - /data/nextcloud/themes:/var/www/html/themes:ro
    depends_on:
      - nextcloud-app
    environment:
      - VIRTUAL_HOST=${OC_DOMAIN}
      - LETSENCRYPT_HOST=${OC_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@***REMOVED***.de
      - LETSENCRYPT_TEST=false

  nextcloud-cron:
    build: ./nextcloud-app
    restart: always
    container_name: nextcloud-cron
    volumes:
      - /data/nextcloud/html:/var/www/html
      - /data/nextcloud/data:/var/www/html/data
      - /data/nextcloud/config:/var/www/html/config
      - /data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/themes:/var/www/html/themes
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis
      
  bitwardenrs:
    image: vaultwarden/server:latest
    container_name: bitwardenrs
    restart: always
    volumes:
      - /data/bitwarden:/data
    expose:
      - 80
    depends_on:
      - letsencrypt
      - mariadb
    environment:
      - VIRTUAL_HOST=${BITWARDEN_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${BITWARDEN_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@***REMOVED***.de
      - LETSENCRYPT_TEST=false
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - DATABASE_URL=${BITWARDEN_DATABASE_URL}

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - letsencrypt
      - mariadb
      - redis
    ports:
      - "8000:8000"
    volumes:
      - /data/paperless/data:/usr/src/paperless/data
      - /data/paperless/media:/usr/src/paperless/media
      - /data/paperless/export:/usr/src/paperless/export
      - /data/paperless/incoming:/usr/src/paperless/consume
    env_file: paperless.env
    environment:
      - LANG=de_DE.UTF-8  
      - LANGUAGE=de_DE.UTF-8 
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_DBENGINE=mariadb
      - PAPERLESS_DBHOST=mariadb-***REMOVED***
      - PAPERLESS_DBUSER=paperless
      - PAPERLESS_DBPASS=***REMOVED***
      - PAPERLESS_DBPORT=3306
      - VIRTUAL_HOST=${PAPERLESS_DOMAIN}
      - LETSENCRYPT_HOST=${PAPERLESS_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@***REMOVED***.de
      - LETSENCRYPT_TEST=false
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    container_name: gotenberg
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: tika
    restart: unless-stopped
