version: '2'

services:

  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-le
    restart: always
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/nginx/acme:/etc/acme.sh
    volumes_from:
      - nginx

  mariadb:
    image: mariadb:10.5
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - /data/mysql:/var/lib/mysql
      - /data/mysql-backup:/var/lib/backup
      - ./mariadb-config:/etc/mysql/conf.d

  redis:
    image: redis
    restart: always
    container_name: redis

  nextcloud-app:
    build: ./nextcloud-app
    restart: always
    container_name: nextcloud-app
    volumes:
      - /data/nextcloud/html:/var/www/html
      - /data/nextcloud/data:/var/www/html/data
      - /data/nextcloud/config:/var/www/html/config
      - /data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/themes:/var/www/html/themes
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
      - redis
      - letsencrypt

  nextcloud-web:
    build: ./nextcloud-web
    restart: always
    container_name: nextcloud-web
    expose:
      - 443
    volumes:
      - /data/nextcloud/html:/var/www/html:ro
      - /data/nextcloud/data:/var/www/html/data:ro
      - /data/nextcloud/config:/var/www/html/config:ro
      - /data/nextcloud/custom_apps:/var/www/html/custom_apps:ro
      - /data/nextcloud/themes:/var/www/html/themes:ro
    depends_on:
      - nextcloud-app
    environment:
      - VIRTUAL_HOST=${OC_DOMAIN}
      - LETSENCRYPT_HOST=${OC_DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
      - LETSENCRYPT_TEST=false

  nextcloud-cron:
    build: ./nextcloud-app
    restart: always
    container_name: nextcloud-cron
    volumes:
      - /data/nextcloud/html:/var/www/html
      - /data/nextcloud/data:/var/www/html/data
      - /data/nextcloud/config:/var/www/html/config
      - /data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/themes:/var/www/html/themes
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis
      
  bitwardenrs:
    image: vaultwarden/server:latest
    container_name: bitwardenrs
    restart: always
    volumes:
      - /data/bitwarden:/data
    expose:
      - 80
    depends_on:
      - letsencrypt
      - mariadb
    environment:
      - VIRTUAL_HOST=${BITWARDEN_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${BITWARDEN_DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
      - LETSENCRYPT_TEST=false
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - DATABASE_URL=${BITWARDEN_DATABASE_URL}

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - letsencrypt
      - mariadb
      - redis
    ports:
      - "8000:8000"
    volumes:
      - /data/paperless/data:/usr/src/paperless/data
      - /data/paperless/media:/usr/src/paperless/media
      - /data/paperless/export:/usr/src/paperless/export
      - /data/paperless/incoming:/usr/src/paperless/consume
    env_file: paperless.env
    environment:
      - LANG=de_DE.UTF-8  
      - LANGUAGE=de_DE.UTF-8 
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_DBENGINE=mariadb
      - PAPERLESS_DBHOST=mariadb
      - PAPERLESS_DBUSER=${PAPERLESS_DBUSER}
      - PAPERLESS_DBPASS=${PAPERLESS_DBPASS}
      - PAPERLESS_DBPORT=${PAPERLESS_DBPORT}
      - VIRTUAL_HOST=${PAPERLESS_DOMAIN}
      - LETSENCRYPT_HOST=${PAPERLESS_DOMAIN}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
      - LETSENCRYPT_TEST=false
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
      - PAPERLESS_URL=https://${PAPERLESS_DOMAIN}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - USERMAP_UID=${USERMAP_UID}
      - USERMAP_GID=${USERMAP_GID}
      - PAPERLESS_OCR_LANGUAGES=${PAPERLESS_OCR_LANGUAGES}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE}
      - PAPERLESS_TIME_ZONE=${PAPERLESS_TIME_ZONE}
      - PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX=${PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX}
      - PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=${PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE}
      - PAPERLESS_CONSUMER_ENABLE_BARCODES=${PAPERLESS_CONSUMER_ENABLE_BARCODES}
      - PAPERLESS_CONSUMER_BARCODE_SCANNER=${PAPERLESS_CONSUMER_BARCODE_SCANNER}

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    container_name: gotenberg
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: tika
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /data/adguard/work:/opt/adguardhome/work
      - /data/adguard/conf:/opt/adguardhome/conf
    network_mode: host
