version: '2'

services:
  
  sbfspotvzsync:
    build: ./sbfspotvzsync
    restart: always
    container_name: sbfspotvzsync
      
# Do not forget to 'docker network create nginx-proxy' before launch, and to add '--network nginx-proxy' to proxied containers.
networks:
  default:
    external:
      name: nginx-proxy

